### ISSUE TITLE
Timezone defaults back to GMT after editing post

### ISSUE THREAD

**Issue by Zorcron** [krisives/cronnit.us#10]
Timezone automatically reverts to GMT after an edit or scheduled comment is saved, and timezone selection is not visible when editing post.

**Comment by krisives** [comment]
Thanks I will look at this.

**Comment by Jurryaany** [comment]
Additionally, posts do not appear to have a timezone field in their dashboard listing at all, I've deducted that they're indeed at GMT.

**Comment by krisives** [comment]
This depends on your browser, specifically if you have Javascript disabled or for some reason your browser will not detect timezone, this is the line of Javascript being ran to determine timezone:

```
/(GMT[\+\-]\d+)/.exec(new Date().toString())[1];
```
This will often produce something like `GMT-700` for example.

**Comment by krisives** [comment]
This should now be solved via d1ab09f51cd7875e1b53ddeaebd4a0856b477313.

This fixes a problem where someone who's browser (for whatever reason) won't detect timezones correctly and has to fill it out manually won't lose the timezone when they later go to edit a post. This also makes it possible for users to change the timezone after the first submission of the post.

**Comment by krisives** [comment]
I have also created a separate enhancement request here: #11
