### ISSUE TITLE
Option to leave the body blanked for subs like r/TodayILearned where no body is allowed

### ISSUE THREAD

**Issue by moshpirit** [krisives/cronnit.us#12]

**Comment by krisives** [comment]
That's a good idea, like a checkbox that says "Allow empty post" ?

**Comment by moshpirit** [comment]
Sure! That would be great 😊

**Comment by Kindred87** [comment]
Any progress on this? @krisives

**Comment by matthewstrasiotto** [comment]
Did this get resolved? If so, I'd like to close this, otherwise I'd like deal with it

**Comment by matthewstrasiotto** [comment]
By the way, there's a reddit API endpoint for checkign this: 
https://www.reddit.com/api/v1/showerthoughts/post_requirements.json

(Useful for validating that a user's submission meets the reqs)

**Comment by moshpirit** [comment]
> Did this get resolved? If so, I'd like to close this, otherwise I'd like deal with it

Seems like it works great to me! :) I think we can close this for now and re-open it in a future if this becomes an issue again. Thanks a lot for the support!!
