### ISSUE TITLE
Increase the character limit of the comments

### ISSUE THREAD

**Issue by specialprograms** [krisives/cronnit.us#14]
Currently there is a very short character limit for comment posts. Not that I'm trying to spam stuff, but the kind of content that I post (mainly recipes) requires more character space due to formatting. I'd love to see the character limit for comment posts expanded. Thanks!

**Comment by krisives** [comment]
Cronnit itself does not put a limit on how long comments can be:

https://github.com/krisives/cronnit.us/blob/master/templates/pages/comment.html#L29

However, Reddit does have a limit AFAIK but we have no control over that.

If you think I have made a mistake please let me know.
