### ISSUE TITLE
Option to clone a post

### ISSUE THREAD

**Issue by moshpirit** [krisives/cronnit.us#18]
Sometimes I like to post the same thing at different times or different subreddits. I think a nice option would be to clone a post so we can edit it and change some stuff even if the post is already done.

**Comment by ExoCode17** [comment]
I second this!

**Comment by mstr3336** [comment]
Oh, this was resolved by #43 :)

**Comment by MLanghof** [comment]
@moshpirit @ExoCode17 Does the post body view from #43 do the job for you? It currently does not support text posts, but that'll come eventually.

**Comment by moshpirit** [comment]
> @moshpirit @ExoCode17 Does the post body view from #43 do the job for you? It currently does not support text posts, but that'll come eventually.

it works great so far, thank you so much!! ❤️

**Comment by MLanghof** [comment]
Alright, great to hear! Closing this for now then.

**Comment by matthewstrasiotto** [comment]
Does this mean we can close #20 too?
