### ISSUE TITLE
Fails to load any pages past landing page

### ISSUE THREAD

**Issue by wagesj45** [krisives/cronnit.us#24]
I followed the instructions on the `README.md` and the landing page will load, but no other pages will load.

**My Config.php**
```
<?php return [
  'client_id' => '[redacted]',
  'client_secret' => '[redacted]',
  'dbdsn' => 'sqlite:foo.db', // you can also use sqlite:foo.db
  'dbuser' => '',
  'dbpass' => '',
  'url' => 'http://localhost:8080'
];
```
**My Apache2 Configuration**
```
Listen 80
Listen 8080

<VirtualHost *:8080>
        DocumentRoot /var/www/cronnit.us/public_html
</VirtualHost>

<VirtualHost *:80>
        # Removed because it is just the default from the vanilla installation.
        DocumentRoot /var/www/html
</VirtualHost>

# vim: syntax=apache ts=4 sw=4 sts=4 sr noet
```
**My file system**
```
[redacted]@seimu:/var/www/cronnit.us$ ls
composer.json  config.php.example  cron.sh     public_html  vendor
composer.lock  Cronnit.php         LICENSE.md  README.md
config.php     cron.php            pages       templates
[redacted]@seimu:/var/www/cronnit.us$ ls pages/
account.php    comment.php    edit.php        home.php    stopnagging.php
admin.php      dashboard.php  faq.php         import.php  submit.php
authorize.php  donate.php     hidethanks.php  logout.php  timezones.php
[redacted]@seimu:/var/www/cronnit.us$ ls public_html/
cronnit.css  cronnit.sql  icon.png  index.php  template.ods
```
**After clicking "Login with Reddit" on the main page**
![image](https://user-images.githubusercontent.com/2460850/71542062-52553280-2927-11ea-8bce-17f520489ef2.png)

**Comment by krisives** [comment]
Try `a2enmod rewrite` to enable mod_rewrite so the URLs are mapped correctly.

Also `sqlite` might not work anymore. There are a few features it doesn't support and I haven't kept track over the years if everything uses only SQLite compatible features.

You can also download a copy of the SQL schema here: http://cronnit.us/cronnit.sql

**Comment by wagesj45** [comment]
Unfortunately after running `a2enmod rewrite` and restarted apache2, the same "Not Found" error persists. I haven't switched off of `sqlite` yet but I don't think that would be causing the rewrite problem.

**Comment by krisives** [comment]
I may not have added the htaccess file I will do so

On Saturday, December 28, 2019, Jordan Wages <notifications@github.com>
wrote:
> Unfortunately after running a2enmod rewrite and restarted apache2, the
same "Not Found" error persists. I haven't switched off of sqlite yet but I
don't think that would be causing the rewrite problem.

**Comment by krisives** [comment]
Hmm, the `.htaccess` does exist and should be rerouting those URLs to `index.php`:

https://github.com/krisives/cronnit.us/blob/master/public_html/.htaccess

You are welcome to PM me on Reddit and we can try to step through the server configuration.
