### ISSUE TITLE
Editing posts while at daily limit fails?

### ISSUE THREAD

**Issue by MLanghof** [krisives/cronnit.us#26]
Apparently a user had a problem where they first scheduled five posts, then tried to edit one of them. They are told that they exceeded their daily post limit.

**Comment by mstr3336** [comment]
Yeah, I've experienced that, I assume that the new submission is made prior to the old submission being removed?

**Comment by MLanghof** [comment]
Ah yes, it's actually just an off-by-one error. The [checkPost](https://github.com/krisives/cronnit.us/blob/ec1606e2f6964e9e0dddd8a2d0e8a19d1b36199d/Cronnit.php#L211) function assumes that a new post is being created but is being also used to check the validity of post edits ([here](https://github.com/krisives/cronnit.us/blob/master/pages/edit.php#L31)). Editing a post while at the daily limit will thus cause a spurious error.
