### ISSUE TITLE
Question: Do cronnit posts originate from the same IP across different accounts? If so, could that lead to spurious ban evasion suspensions on Reddit's end?

### ISSUE THREAD

**Issue by mstr3336** [krisives/cronnit.us#28]
Hi there!
I've been using cronnit to help post regularly to certain communities with updates, promotions, etc. 

My account was banned from a prominent community due to a community rule that promotional accounts were not allowed in that community. I was okay with that, and gave it little thought, but then recently I recieved a 7 day suspension for engaging in "ban evasion" on that community. None of my alts or other accounts have enaged with it.

It caught me totally off-guard, but apparently [reddit has recently implemented a proactive autodetection/suspension system for ban evasion](https://www.reddit.com/r/redditsecurity/comments/gsgg6k/improved_ban_evasion_detection_and_mitigation/). The system is still relatively immature, and I've seen at least a few instances of other false positives.

Probably a good thing, but in this instance I've been racking my brain to understand how an account engaging with this community was linked to mine. 

Weirdly enough, my **Actual** connected accounts have not recieved any suspension, and these accounts have never posted via Cronnit.

Eventually, it did occur to me that cronnit's server may be triggering this BE detection system, as it likely has a static IP that issues requests from many different accounts.

I thought I'd raise this issue here, though I'm not sure if it's actually a factor, to see what you think, and whether you might be interested in following up with Admin. 

Also I'd like this to serve as a warning that using cronnit MIGHT trigger spurious suspension of your accounts, though I'm not sure

**Comment by bdlowery** [comment]
So did you ever figure out the issue? Was it cronnit?

**Comment by matthewstrasiotto** [comment]
Nah, i remembered that Reddit's CDN was down in my state so I used a VPN to access reddit, and i think the VPN was probably responsible for the fingerprint mixup

**Comment by bdlowery** [comment]
Alright cool, don't want to get ip banned because someone else using cronnit got banned. Thanks for clarifying.

**Comment by MLanghof** [comment]
I have seen several Cronnit users suspended by reddit (for good reasons - as you can probably imagine, this kind of tool also attracts actual spammers, which is coincidentally why the daily limit exists). But in the two years so far, there has been no indication that this impacts other legitimate Cronnit users.

So, empirically speaking, you shouldn't have to worry about this.
