### ISSUE TITLE
On my account with quite a lot of posts, thumbnails don't seem to work at all

### ISSUE THREAD

**Issue by matthewstrasiotto** [krisives/cronnit.us#47]
On one of my accounts, (but others for some reason?) thumbnails don't seem to work at all, under any view- 

From memory, briefly checking it out a few days prior on my phone on the same account, everything seemed fine, but now the thumbnail containing `<div>` appears totally empty, for all posts. 

I really can't figure out why, but the account DOES have > 100 posts (Much more than I tested the feature on). 

I have to imagine that either some post is in some way breaking the regex in the rendering, or some other edge case is somehow being triggered

**Comment by MLanghof** [comment]
Yep. We did our best to make it not load everything, but it just doesn't work reliably (neither from `loading="lazy"` nor from `?autoplay=0`) and thus people with hundreds or even thousands of videos couldn't load their dashboard at all. As a quick-fix I changed the thumbnails to only be generated for users with < 100 posts, with the intention to implement pagination this week.

**Comment by mstr3336** [comment]
AH I see, thanks Max - It's not a bug, it's a feature :stuck_out_tongue: 
Do you happen to have a vague sense of the best way to implement pagination? 
Something like passing page number in the url query `?page=2` , and then 
I can have a crack at it ASAP

**Comment by MLanghof** [comment]
~~Well bootstrap provides pagination buttons but you still have to supply the functionality behind it.~~ Exactly.

> I already discussed the approach with Kris, so I can quote him here:
> 
> Pagination should be pretty easy. In dashboard.php get a page number from the user:
> 
>     $pageNumber = intval(@$_GET['page']);
> 
> I would avoid using the variable name "$page", since it may have been used in the scope that is doing the include "$page.php"; in Cronnit.php.
> 
> Then the SQL that is needed is something like:
> 
>     SELECT * FROM blah LIMIT $offset, $pageSize
> 
> In a perfect world that last part would become "LIMIT ?, ?" or similar, but AFAIK MySQL (for whatever reason) doesn't allow those parts of the query to be prepared statement variables, but just make sure they are ints:
> 
>     $pageSize = 50;
>     $offset = $pageNumber * $pageSize;
> 
> Rendering the Pagination HTML tabs is more or less an exercise in Twig:
> 
> 
> ```
> <ol class="pagination">
> {% for i in range(0, pageCount) %}
>    <li {{ i == activePage ? 'class="active"' : '' }}>
>       <a href="/dashboard?page={{ i }}">{{ i }}</a>
>    </li>
> {% endfor %}
> </ol>
> ```
>  
> Or something kind of close to that.

**Comment by mstr3336** [comment]
Shall we migrate this discussion to #21 ?

**Comment by MLanghof** [comment]
Right. Moving that quote.

**Comment by matthewstrasiotto** [comment]
Closing this, since it's not really codebase related & it's reasoning is well documented elsewhere

**Comment by MLanghof** [comment]
...and it should be alleviated. Right?

**Comment by matthewstrasiotto** [comment]
Yeah, i have thumbs again
