### ISSUE TITLE
On content view, adding a new post just duplicates the horizontal rule until you refresh

### ISSUE THREAD

**Issue by matthewstrasiotto** [krisives/cronnit.us#54]
The update to the view isn't rendered correctly since the addition of the horizontal rule in https://github.com/krisives/cronnit.us/commit/ad81381382ceaf61beec42b1b32ddfea1c4ced7c

The line that introduces this bug:

https://github.com/krisives/cronnit.us/blob/6ebff918df4e495dd8260d6b663bbddd419e5bb5/templates/posts-body.html#L29

The problem is that the current behaviour for onSubmit was to submit the form to the endpoint, and then select the previous sibling, duplicate it, and replace its data with the data from the form. 

Instead, it's selecting a horizontal rule.

**Comment by matthewstrasiotto** [comment]
Should be resolved by #56 , but I think I noticed this behaviour was still on the site. 
That said, the site isn't always the same tree as master, sometimes there are hotfixes etc.

**Comment by MLanghof** [comment]
Oh right, I just haven't pulled this, should be live now. Thanks for the reminder!
