### ISSUE TITLE
Suggestion: Import using TSV

### ISSUE THREAD

**Issue by Jurryaany** [krisives/cronnit.us#64]
CSV is great for bulk imports, but it does not allow for post titles or descriptions with commas in them.
TSV (tab-separated values) would be a great alternative format to be able to use.
It probably isn't perfect for all post types either, but it would allow for greater flexibility when bulk importing.

**Comment by MLanghof** [comment]
CSV definitely allows commas in post titles and descriptions:

https://stackoverflow.com/questions/4617935/is-there-a-way-to-include-commas-in-csv-columns-without-breaking-the-formatting

Your spreadsheet editing software should hopefully apply quotes where necessary when exporting to CSV.

Fun fact: This is one of the main things that makes fast *and* correct CSV parsing very difficult - you can't just split by commas.

**Comment by matthewstrasiotto** [comment]
> Fun fact: This is one of the main things that makes fast _and_ correct CSV parsing very difficult - you can't just split by commas.

Fun fact: the CSV format is really quite bad.

I think this issue should be closed since it doesn't apply

**Comment by krisives** [comment]
> Fun fact: the CSV format is really quite bad.

I disagree. The format is actually quite simple and useful. The problem is that the most popular product that exists, Microsoft Office, is terrible at it - because they are highly incentivized to not support it well.
