### ISSUE TITLE
Remove /r/ prefix on subreddits, introduce subreddit validation

### ISSUE THREAD

**Issue by kittywhiskers** [krisives/cronnit.us#70]
Currently, you enter a subreddit name using `/r/subredditname`, introducing confusion between possible inputs `r/name`, `/r/name`, `/r/name/`. A simpler solution would be to set subreddit name as `subredditname` directly and introduce validation, allowing only `_` and client-side validation to ensure that the subreddit exists.

### Current Behaviour

* Subreddit can be entered in multitudes of ways
* No validation to ensure that subreddit is valid

![Invalid Subreddit Name](https://user-images.githubusercontent.com/63189531/103222553-74bec900-494a-11eb-9a5a-760b6f2351cf.png)

### Proposed Behaviour

* Forcing subreddit client-side validation, server-side validation to remove useless queries from queue
* Subreddit can be entered only in a singular manner

**Comment by MLanghof** [comment]
I agree that validation should exist to prevent mistakes. But I don't see the benefit of forcing users to type it in exactly one specific way. If it's unambiguous what the user meant, why reject it?

**Comment by kittywhiskers** [comment]
It introduces additional overhead because of multiple variants during validation and I don't know if the API call is fault tolerant with those various variants (single slash, double slash, triple slash, only subreddit name) but disregarding that, client-side JavaScript that checks only if accepted characters are present would be much more uncomplicated.

It's a matter of design preference I guess but I'd prefer having a singular consistent format

**Comment by matthewstrasiotto** [comment]
Hard disagree on your proposed handling of variability in input - it doesn't at all matter if the user inputs any of the following:

`r/DnD` `/r/DnD` `DnD`, `/DnD` - The intention is eminently clear, they want to post to DnD.

I can't remember if I proposed it, but a client-side preview of the post destination would probably be helpful in validating the destination exists, like laterforreddit does.

**Comment by kittywhiskers** [comment]
> I can't remember if I proposed it, but a client-side preview of the post destination would probably be helpful in validating the destination exists, like laterforreddit does.

As long as this is done and the content isn't being posted on the wrong subreddit, the objective is being fulfilled

**Comment by matthewstrasiotto** [comment]
As for handling of different inputs, on the client side it can be as simple as stripping out a leading "/?r/", then validating the rest some other way (alphanumeric check, query reddit, however its approached)

Related: #41 - Client side validation has been requested for a while. I stopped using cronnit for ages so stopped working on it, though.

**Comment by kittywhiskers** [comment]
Sounds good to me!

**Comment by matthewstrasiotto** [comment]
> Sounds good to me! Though once it is posted, I hope it can format the subreddit column at the overview page consistently so it doesn't look like this...
> 
> ![](https://user-images.githubusercontent.com/63189531/103222731-ae8fcf80-494a-11eb-8e74-cf7886c852a4.png)



Well, for the example you've given the client-side implementation I'm imagining would probably POST `a352` and `aaaaaa` after stripping the `/r/` prefix. 

I agree with your call for server-side validation, however, since, of course, not all POSTs come from the web client

**Comment by krisives** [comment]
The reason all of these work is because the Reddit API allows all of them. I would rather not impose artificial restrictions and just let people use the API.
