### ISSUE TITLE
UI: Date Format not explicitly specified on post timing page

### ISSUE THREAD

**Issue by kittywhiskers** [krisives/cronnit.us#72]
The date entry format seems to be `MM/DD/YYYY` and that introduces confusion for people who use different date formats, ideally you would localize to the date and time standard used in different countries but a quicker fix would be to explicitly specify it instead.

### Current Behaviour

![Current](https://user-images.githubusercontent.com/63189531/103223166-a5ebc900-494b-11eb-9e57-726912169c08.png)

### Expected Behaviour

![Expected](https://user-images.githubusercontent.com/63189531/103223206-b7cd6c00-494b-11eb-9b8d-3aa5eb26e0c6.png)

**Comment by MLanghof** [comment]
The current date picker is just what the HTML5 standard provides. There are probably libraries out there that improve on it, but I'd definitely want to leave localization of this kind of thing to the browser as much as possible.

When creating a new post, the form starts off like this for me, which is unambiguous:

![image](https://user-images.githubusercontent.com/6524684/103293314-ea30a500-49ef-11eb-98d6-defa9f52fff0.png)

Same for the inline post scheduling in the content-grouped dashboard view.

I do agree that this is less clear in the edit page. Still, your browser should open a date picker when interacting with this input.

---

Overall, it's certainly a bit of an awkward situation to have dates in different formats across the site. I guess adding these UI reminders won't hurt, so I'll merge this.
