### ISSUE TITLE
Lack of a responsible disclosure policy

### ISSUE THREAD

**Issue by kittywhiskers** [krisives/cronnit.us#73]
To setup a security policy for this repository, see [Adding a security policy to your repository](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository).

Current I have no way of contacting the author to report vulnerabilities and I'd rather not disturb the developer on their personal account, it seems discourteous. A reward is not necessary to make a security policy, just an email address and politeness goes a long way!

EDIT: Bad Markdown

**Comment by MLanghof** [comment]
cronnit.us itself guides people to `support@cronnit.us` (or to /u/KayRice). The commits themselves also have associated email addresses when in doubt.

I feel that adding such a policy is sort of overkill, but I guess it's not a big task. Will look into it.

**Comment by kittywhiskers** [comment]
> `support@cronnit.us`

I presume that's for support queries. AFAIK most services have a distinct email address for security correspondences. 

> The commits themselves also have associated email addresses when in doubt.

Is the developer okay with being contacted on their personal email for one of the projects? If so, then I'd say that's okay but having that explicitly written out helps.

**Comment by matthewstrasiotto** [comment]
This seems very reasonable. 
Related #62

**Comment by matthewstrasiotto** [comment]
In my case, the only reason I ever had personal emails on my commits was a mistake, I wouldn't operate under the assumption that devs will be contactable via commit emails.

I doubt the support email address is so inundated presently that security emails can't be triaged, though.

**Comment by krisives** [comment]
Right now there are a few different channels available. I can throw something into the FAQ about this since it doesn't hurt.
